services:
  library-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: library-service
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - readstack-network

  mysql:
    image: mysql:8.4
    container_name: library-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${DATABASE_ROOT_PASSWORD}"]
      timeout: 5s
      interval: 10s
      retries: 10
    networks:
      - readstack-network

  adminer:
    image: adminer:latest
    container_name: library-adminer
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    networks:
      - readstack-network

networks:
  readstack-network:
    driver: bridge

volumes:
  mysql-data:
