spring:
  application:
    name:
      library-service
  profiles:
    active: local
  security:
    user:
      name: local
      password: local
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://mysql:3306/librarydb}
    username: ${DATABASE_USERNAME:libuser}
    password: ${DATABASE_PASSWORD:libpass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

custom:
  database:
    root-password: ${DATABASE_ROOT_PASSWORD:secret}

logging:
  level:
    root: INFO
    com.readstack.library: DEBUG
    com.readstack.library.hello: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.session: DEBUG

server:
  port: 8080
